# Generated by Django 4.0.6 on 2022-07-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
    ]
