# Generated by Django 4.0.6 on 2022-07-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
